- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: myjdownloader

- name: Stop and remove any existing container
  docker_container:
    name: myjdownloader
    state: absent

- name: Create myjdownloader directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/myjdownloader/config/libs

- name: Import 7zip 1509
  copy:
    src: "sevenzipjbinding1509.jar"
    dest: "/opt/myjdownloader/config/libs/sevenzipjbinding1509.jar"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: no

- name: Import 7zip 1509Linux
  copy:
    src: "sevenzipjbinding1509Linux.jar"
    dest: "/opt/myjdownloader/config/libs/sevenzipjbinding1509Linux.jar"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0775
    force: no

- name: Create and start container
  docker_container:
    name: myjdownloader
    image: "jlesage/jdownloader-2:latest"
    pull: yes
    published_ports:
      - "127.0.0.1:5800:5800"
      - "127.0.0.1:5900:5900"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/local/downloads/myjdownloader/output:/output:rw"
      - "/mnt:/mnt:rw"
      - "/opt/myjdownloader/config:/config:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      VIRTUAL_HOST: "myjdownloader.{{domain}}"
      VIRTUAL_PORT: 5800
      LETSENCRYPT_HOST: "myjdownloader.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
      DISPLAY_WIDTH: 1280
      DISPLAY_HEIGHT: 768
      VNC_PASSWORD: "{{passwd}}"
      USER_ID: "{{uid}}"
      GROUP_ID: "{{gid}}"
      CLEAN_TMP_DIR: 1
      UMASK: 000
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - myjdownloader
    purge_networks: yes
    restart_policy: always
    state: started
