#########################################################################
# Title:         Community: Telly | Telly 1.5                           #
# Author(s):     EnorMOZ, Desimaniac                                    #
# URL:           https://github.com/Cloudbox/Community                  #
# Docker Image:  tellytv/telly                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Version Info
  debug:
    msg: "Installing Telly version: {{ telly.version }}"

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    record: telly
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: telly
    state: absent

- name: Create telly directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - "/opt/telly"
    - "/opt/telly/telly.db"

- name: Create and start container
  docker_container:
    name: telly
    image: "tellytv/telly:v1.5.0"
    pull: yes
    user: "{{ uid }}:{{ gid }}"
    command: --database.file="/telly/telly.db"
    env:
      TZ: "{{ tz }}"
      TELLY_LOG_LEVEL: "debug"
      VIRTUAL_HOST: "telly.{{ user.domain }}"
      VIRTUAL_PORT: "6077"
      LETSENCRYPT_HOST: "telly.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/opt/telly/telly.db:/telly/"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - telly
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
