#########################################################################
# Title:            Community: qbittorrentX                             #
# Author(s):        Kromo                                               #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  sc4h/qbittorrent                             #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Gather list of qbittorrentx Docker containers"
  shell: "docker ps -a --format '{{ '{{' }} .Names{{ '}}' }}' --filter label=com.github.cloudbox.community=qbittorrentx | xargs echo -n"
  register: cloudbox_community_qbittorrentx
  ignore_errors: yes

- name: "Stop all qbittorrentx Docker containers"
  shell: "docker stop {{ cloudbox_community_qbittorrentx.stdout }}"
  ignore_errors: yes
  when: (cloudbox_community_qbittorrentx.stdout | trim | length > 0)

- name: "Remove all qbittorrentx Docker containers"
  shell: "docker rm {{ cloudbox_community_qbittorrentx.stdout }}"
  ignore_errors: yes
  when: (cloudbox_community_qbittorrentx.stdout | trim | length > 0)

- name: "Execute qbittorrentX roles"
  include_tasks: template.yml
  vars:
    rolename: "{{ role }}"
    roleport: "{{ 56881 + index }}"
  with_items: "{{ qbittorrentx.roles }}"
  loop_control:
    loop_var: role
    index_var: index
