#########################################################################
# Title:            Community: WordPress                                #
# Author(s):        Migz93                                              #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  wordpress                                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: MariaDB Role
  include_role:
    name: mariadb

- name: "sleep for 20 seconds and continue"
  wait_for: timeout=20

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    record: "{{ wordpress.subdomain|default('wordpress',true) }}"
  when: cloudflare_enabled

- name: Stop and remove any existing containers
  docker_container: "name={{ item }} state=absent"
  with_items:
    - wordpress

- name: Create required directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/wordpress

- name: Create and start wordpress container
  docker_container:
    name: wordpress
    image: "wordpress"
    pull: yes
    user: "{{ uid }}:{{ gid }}"
    env:
      TZ: "{{ tz }}"
      WORDPRESS_DB_HOST: "mariadb:3306"
      WORDPRESS_DB_USER: "root"
      WORDPRESS_DB_PASSWORD: "password321"
      WORDPRESS_DB_NAME: "wordpress"
      VIRTUAL_HOST: "{{ wordpress.subdomain|default('wordpress',true) }}.{{ user.domain }}"
      VIRTUAL_PORT: "80"
      VIRTUAL_PROTO: "http"
      LETSENCRYPT_HOST: "{{ wordpress.subdomain|default('wordpress',true) }}.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/opt/wordpress:/var/www/html"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - wordpress
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
