- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: mellow

- name: Stop and remove any existing container
  docker_container:
    name: mellow
    state: absent

- name: Create mellow directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/mellow

- name: Create and start container
  docker_container:
    name: mellow
    image: voidp/mellow
    pull: yes
    published_ports:
      - "127.0.0.1:5060:5060"
    env:
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      VIRTUAL_HOST: "mellow.{{domain}}"
      VIRTUAL_PORT: 5060
      LETSENCRYPT_HOST: "mellow.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/mellow:/usr/src/app/data/"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - mellow
    restart_policy: always
    state: started
