#########################################################################
# Title:            Community: Coder                                    #
# Author(s):        astroMD                                             #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  codercom/code-server                                #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: coder
  when: cloudflare_enabled

- name: Stop and remove any existing containers
  docker_container: "name={{ item }} state=absent"
  with_items:
    - coder

- name: Create required directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/coder

- name: Create and start coder container
  docker_container:
    name: coder
    image: "codercom/code-server"
    pull: yes
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      PASSWORD: "{{ user.pass }}"
      VIRTUAL_HOST: "coder.{{ user.domain }}"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "coder.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/home/{{ user.name }}/workspaces:/home/coder/project"
      - "/mnt:/mnt"
      - "/opt:/host_opt"
      - "/home/{{ user.name }}:/home/coder/host"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - coder
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
