- name: "Install named bazarr role"
  debug:
    msg: "Installing {{ rolename }} using port {{ roleport }}"

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: "bazarr{{ rolename }}"
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: "bazarr{{ rolename }}"
    state: absent

- name: Create bazarrx directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ user }}"
  with_items:
    - "/opt/bazarr{{ rolename }}"

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/bazarr{{ rolename }}:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/TV:/tv"
      - "/mnt/unionfs/Media/Movies:/movies"
     
- name: Create and start container
  docker_container:
    name: "bazarr{{ rolename }}"
    image: "linuxserver/bazarr"
    pull: yes
    published_ports:
      - "127.0.0.1:{{ roleport }}:6767"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "bazarr{{ rolename }}.{{ domain }}"
      VIRTUAL_PORT: 6767
      LETSENCRYPT_HOST: "bazarr{{ rolename }}.{{ domain }}"
      LETSENCRYPT_EMAIL: "{{ email }}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - "bazarr{{ rolename }}"
    purge_networks: yes
    restart_policy: always
    state: started
