#########################################################################
# Title:            Community: BazarrX | Template                       #
# Author(s):        Migz93                                              #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  lscr.io/linuxserver/bazarr                                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Install named bazarr role"
  debug:
    msg: "Installing {{ rolename }}"

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    record: "bazarr{{ rolename }}"
  when: cloudflare_enabled

- name: Create bazarrx directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - "/opt/bazarr{{ rolename }}"

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/bazarr{{ rolename }}:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/TV:/tv"
      - "/mnt/unionfs/Media/Movies:/movies"

- name: Create and start container
  docker_container:
    name: "bazarr{{ rolename }}"
    image: "cr.hotio.dev/hotio/bazarr:{{ bazarrx.version }}"
    pull: yes
    exposed_ports:
      - "6767"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "bazarr{{ rolename }}.{{ user.domain }}"
      VIRTUAL_PORT: "6767"
      LETSENCRYPT_HOST: "bazarr{{ rolename }}.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "com.github.cloudbox.community": "bazarrx"
    networks:
      - name: cloudbox
        aliases:
          - "bazarr{{ rolename }}"
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
