#########################################################################
# Title:            Community: Handbrake                                #
# Author(s):        Satz                                                #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  jlesage/handbrake                                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: handbrake
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: handbrake
    state: absent

- name: Create handbrake directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/handbrake

- name: "Check if '/dev/dri' exists"
  stat:
    path: "/dev/dri"
  register: dev_dri

- name: Create and start container
  docker_container:
    name: handbrake
    image: jlesage/handbrake
    pull: yes
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "handbrake.{{ user.domain }}"
      VIRTUAL_PORT: "5800"
      LETSENCRYPT_HOST: "handbrake.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      CLEAN_TMP_DIR: "1"
      ENABLE_CJK_FONT: "1"
    volumes:
      - "/opt/handbrake:/config:rw"
      - "/mnt:/storage:ro"
      - "/mnt/local/downloads/handbrake/watch:/watch:rw"
      - "/mnt/local/downloads/handbrake/output:/output:rw"
    devices: "{{ '/dev/dri:/dev/dri' if (gpu.intel and dev_dri.stat.exists) | default(false) else omit }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - handbrake
    exposed_ports:
      - 5800
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
