#########################################################################
# Title:            Community: Kitana                                   #
# Author(s):        4everfun                                            #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  pannal/kitana                                       #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    record: kitana
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: kitana
    state: absent

- name: Create kitana directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/kitana

- name: Create and start container
  docker_container:
    name: kitana
    image: "pannal/kitana:latest"
    pull: yes
    env:
      TZ: "{{ tz }}"
      VIRTUAL_HOST: "kitana.{{ user.domain }}"
      VIRTUAL_PORT: "31337"
      LETSENCRYPT_HOST: "kitana.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    command: -P
    volumes:
      - "/opt/kitana:/app/data"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - kitana
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
