---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: filebrowser
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: filebrowser
    state: absent

- name: Create opt directory
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/filebrowser

- name: "Check if filebrowser env file exists"
  stat:
    path: "/opt/filebrowser/filebrowser.json"
  register: filebrowser_env

- name: "Check if filebrowser database file exists"
  stat:
    path: "/opt/filebrowser/filebrowser.db"
  register: filebrowser_db

- name: "Import env file if it doesnt exist"
  template:
    src: filebrowser.json.j2
    dest: /opt/filebrowser/filebrowser.json
    force: yes
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
  when: not filebrowser_env.stat.exists
  
- name: "Import database if it doesnt exist"
  file:
    src: filebrowser.db
    dest: /opt/filebrowser/filebrowser.db
    force: yes
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
  when: not filebrowser_db.stat.exists

- name: Create and start container
  docker_container:
    name: filebrowser
    image: filebrowser/filebrowser:latest
    pull: yes
    env:
      VIRTUAL_HOST: "filebrowser.{{ user.domain }}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "filebrowser.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/filebrowser/filebrowser.db:/database.db
      - "/opt/filebrowser/filebrowser.json:/.filebrowser.json"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    user: "{{ uid }}:{{ gid }}"
    networks:
      - name: cloudbox
        aliases:
          - filebrowser
    restart_policy: always
    state: started
