- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: sonarr1080

- name: Stop and remove any existing container
  docker_container:
    name: sonarr1080
    state: absent

- name: Create sonarr1080 directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/sonarr1080

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/sonarr1080:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/TV:/tv"

- name: Create and start container
  docker_container:
    name: sonarr1080
    image: "hotio/sonarr"
    pull: yes
    published_ports:
      - "127.0.0.1:8991:8989"
    env:
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid}}"
      PGID: "{{gid}}"
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "sonarr1080.{{domain}}"
      VIRTUAL_PORT: 8989
      LETSENCRYPT_HOST: "sonarr1080.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - sonarr1080
    purge_networks: yes
    restart_policy: always
    state: started
