- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: monitorr

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: monitorr
    state: absent

- name: Create monitorr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/monitorr

- name: Create and start container
  docker_container:
    name: monitorr
    image: monitorr/monitorr:develop
    pull: yes
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "monitorr.{{domain}}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "monitorr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/monitorr:/app"
    networks:
      - name: cloudbox
        aliases:
          - monitorr
    restart_policy: always
    state: started
