- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: goplaxt
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: goplaxt
    state: absent

- name: Create goplaxt directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ user }}"
  with_items:
    - /opt/goplaxt

- name: Create and start container
  docker_container:
    name: goplaxt
    image: xanderstrike/goplaxt
    pull: yes
    published_ports:
      - "127.0.0.1:8000:8000"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "goplaxt.{{ domain }}"
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: "goplaxt.{{ domain }}"
      LETSENCRYPT_EMAIL: "{{ email }}"
      TRAKT_ID: "{{ goplaxt.trakt_id }}"
      TRAKT_secret: "{{ goplaxt.trakt_secret }}"
      REDIRECT_URI: "https://goplaxt.{{ domain }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/goplaxt:/app/keystore"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - goplaxt
    purge_networks: yes
    restart_policy: always
    state: started
