#########################################################################
# Title:         Community: xTeve | Migration Tasks                     #
# Author(s):     Satz                                                   #
# URL:           https://github.com/Cloudbox/Community                  #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Check folder exists
  stat:
    path: /opt/xteve
  register: folder

- name: Check subfolder exists
  stat:
    path: /opt/xteve/app
  register: subfolder

- name: Move '/opt/xteve' folder contents to 'tmp'
  shell: |
    mv /opt/xteve/app /tmp/app
    mkdir /opt/xteve
    mv /tmp/app /opt/xteve/
    find /opt/xteve/* -type d -empty -delete
    chown -R {{ user.name }}:{{ user.name }} /opt/xteve
  when: (folder.stat.exists) and (subfolder.stat.exists)
