#########################################################################
# Title:            Cloudbox Community: xTeVe                           #
# Author(s):        Superduper09                                        #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  bl0m1/xtevedocker                                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: xteve
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: xteve
    state: absent

- name: Create xteve directory
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/xteve
    - /opt/xteve/tmp

- name: Create and start container
  docker_container:
    name: xteve
    image: bl0m1/xtevedocker
    pull: yes
    published_ports:
      - "0.0.0.0:34400:34400"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "xteve.{{ user.domain }}"
      VIRTUAL_PORT: 34400
      LETSENCRYPT_HOST: "xteve.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/xteve:/root/xteve"
      - "/opt/xteve/tmp:/tmp/xteve"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - xteve
    purge_networks: yes
    restart_policy: always
    state: started
