#########################################################################
# Title:            Community: LazyLibrarian                            #
# Author(s):        Superduper09                                        #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  thraxis/lazylibrarian-calibre                       #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: lazylibrarian
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: lazylibrarian
    state: absent

- name: Create lazylibrarian directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/lazylibrarian

- name: Create and start container
  docker_container:
    name: lazylibrarian
    image: thraxis/lazylibrarian-calibre
    pull: yes
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "lazylibrarian.{{ user.domain }}"
      VIRTUAL_PORT: "5299"
      LETSENCRYPT_HOST: "lazylibrarian.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
    volumes:
      - "/opt/lazylibrarian:/config"
      - "/mnt:/mnt"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - lazylibrarian
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
